#!/usr/bin/env python3
"""Generate `Docs/fx-library.md` from the registered FX library.

Run from anywhere::

    python3 Docs/tools/scripts/gen_fx_library.py

The generator imports `nocturnation_orchestrator.fx.library` (which
triggers self-registration of every FX) and walks the canonical
`fx_registry`. Output is deterministic: FX are listed by id within
each category, and the header / footer are static. Re-running the
script overwrites the file with the same bytes when nothing has
changed - safe to run in pre-commit.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add Docs/tools to sys.path so the orchestrator package imports.
_TOOLS_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_TOOLS_DIR))

from nocturnation_orchestrator.fx import library as _library  # noqa: F401
from nocturnation_orchestrator.fx.params import validate_params_attr
from nocturnation_orchestrator.fx.registry import fx_registry


OUTPUT_PATH = _TOOLS_DIR.parent / "fx-library.md"


HEADER = """# FX Library

This file is generated by `Docs/tools/scripts/gen_fx_library.py` from
the FX classes in `Docs/tools/nocturnation_orchestrator/fx/library/`.
Do not edit by hand; update the FX class metadata and re-run the
generator.

## Cue file format

Each song lives in `Docs/songs/<artist>-<title>.cues`. The orchestrator
matches the now-playing track to a file via fuzzy match on artist and
title; `_default.cues` is the fallback.

Format: one cue per line. Whitespace separates fields (one or more
spaces, or tabs - whatever keeps the columns tidy). `#` starts a
comment - place comments on their own line between cues to mark
sections / lyrics, or trail one off the end of a cue.

```
# Coldplay - Fix You
@bpm 138
@default_fx quiet_wash

# --- Intro ---
00:00     quiet_wash       20  40 80
# "When you try your best..."
00:13.40  sparkle_on_beat  80  200 200 100   # centisecond grain
00:35.5   sparkle_on_beat  255 0   255 100   # tenths

# --- Build ---
01:20     linear_buildup   255 0   0   100 64  --buildup 8

# --- Drop ---
01:28     strobe_burst     5   255
01:30.250 sparkle_on_beat  255 255 255 100   # millisecond grain

# --- Outro ---
02:55     fade_to_black                       --buildup 4
03:00     stop
```

### Directives (`@`)

| Directive       | Purpose                                                  |
|-----------------|----------------------------------------------------------|
| `@bpm N`        | Default BPM for cues that do not override.               |
| `@default_fx N` | FX run before the first cue and after `stop` (id or name). |
| `@artist X`     | Free-text artist label (used by the matcher).            |
| `@title X`      | Free-text title label (used by the matcher).             |
| `@offset S.SS`  | Shift every cue + lyric by S.SS seconds (signed). Used to compensate for album-mastering silence padding. |

### Cue line

`MM:SS` (or `H:MM:SS`) optionally with up to three fractional-second
digits (`MM:SS.x`, `MM:SS.xx`, `MM:SS.xxx`), followed by the FX
`cue_name`, then up to six positional params, then optional
`--bpm N` / `--buildup N` overrides. Trailing reserved params can be
omitted entirely.

At 120 BPM each beat is 500 ms, so a one-second granularity drifts
the lighting two beats off the music. Use fractional seconds for
beat-aligned cues; centisecond grain matches LRC timestamps so a
skeleton from `gen_cues_skeleton.py` can be edited in place.

`stop` is the cancel sentinel - equivalent to `runner.start(fx_id=0)`.

### Param units

| Unit      | Cue-file range | On the wire (u8)              |
|-----------|----------------|-------------------------------|
| `u8`      | 0..255         | as-is                         |
| `percent` | 0..100         | `round(v * 255 / 100)`        |
| `count`   | 0..255         | as-is (FX validates its max)  |
| `100ms`   | 0..255         | 1..255 = 100 ms..25.5 s       |

The cue line carries human values (`probability 100` means 100%); the
loader converts to u8 before calling the FX's `start()`.

---

"""


def _md_table(rows):
    """Render a list of [col1, col2, col3] rows as a markdown table.

    The first row is the header. Pads columns for alignment.
    """
    if not rows:
        return ""
    widths = [max(len(str(r[i])) for r in rows) for i in range(len(rows[0]))]
    out = []
    out.append("| " + " | ".join(
        str(rows[0][i]).ljust(widths[i]) for i in range(len(widths))
    ) + " |")
    out.append("|" + "|".join("-" * (w + 2) for w in widths) + "|")
    for row in rows[1:]:
        out.append("| " + " | ".join(
            str(row[i]).ljust(widths[i]) for i in range(len(widths))
        ) + " |")
    return "\n".join(out)


def _render_fx(cls):
    """Render the markdown section for one FX class."""
    validate_params_attr(cls)
    lines = []
    lines.append("### %s (id %d)" % (cls.name, cls.id))
    lines.append("")
    lines.append("`%s` - %s" % (cls.cue_name, cls.category))
    lines.append("")
    lines.append(cls.description)
    lines.append("")

    rows = [["Slot", "Name", "Unit", "Description"]]
    for i, (name, unit, desc) in enumerate(cls.PARAMS):
        if name is None:
            rows.append([str(i), "_reserved_", "-", desc])
        else:
            rows.append([str(i), name, unit, desc])
    lines.append(_md_table(rows))
    lines.append("")
    return "\n".join(lines)


CATEGORY_ORDER = ("ambient", "beat", "buildup", "drop", "transition")


def build_doc():
    """Render the full markdown doc and return it as a string."""
    out = [HEADER]

    by_category = {c: [] for c in CATEGORY_ORDER}
    extra = {}  # category -> list, for any categories outside CATEGORY_ORDER
    for fx_id in fx_registry.all_ids():
        cls = fx_registry.get(fx_id)
        if cls.category in by_category:
            by_category[cls.category].append(cls)
        else:
            extra.setdefault(cls.category, []).append(cls)

    def render_section(category, items):
        items = sorted(items, key=lambda c: c.id)
        if not items:
            return
        out.append("## %s\n" % category.capitalize())
        for cls in items:
            out.append(_render_fx(cls))

    for category in CATEGORY_ORDER:
        render_section(category, by_category[category])
    for category in sorted(extra):
        render_section(category, extra[category])

    out.append("---\n")
    out.append("Generated by `Docs/tools/scripts/gen_fx_library.py`. "
               "Edit the FX classes, not this file.\n")
    return "\n".join(out)


def main():
    doc = build_doc()
    OUTPUT_PATH.write_text(doc)
    print("Wrote %s (%d FX, %d bytes)" % (
        OUTPUT_PATH, len(fx_registry.all_ids()), len(doc)))


if __name__ == "__main__":
    main()
