"""FX engine (Epic 10 B1).

Each FX subclasses `Fx` and writes DMX channel values into a 512-byte
universe bytearray on every `tick(now_ms, universe)`. The orchestrator
ticks the engine at ~50 Hz between OS now-playing polls, then hands
the universe to the output dispatcher.

Adding a new effect = subclass `Fx`, decorate with
`@fx_registry.register`. See `Docs/fx-library.md` (generated by B4)
for the per-effect contract.
"""

from .base import Fx
from .registry import FxRegistry, fx_registry
from .runner import FxRunner

__all__ = [
    "Fx",
    "FxRegistry",
    "fx_registry",
    "FxRunner",
]
